FROM golang:1.18-alpine 
WORKDIR /app
COPY go.mod go.sum ./
# fetch dependancies
RUN go mod download && \
    go mod verify
RUN apk --no-cache update && \
apk --no-cache add git gcc libc-dev
# copy the source code as the last step
COPY . .
# build binary
RUN CGO_ENABLED=1 GOOS=linux go build -tags musl -ldflags="-w -s -v" -a -installsuffix cgo -o /app/crawl 
